### Info
GET http://localhost:3003/api/blogs

### Get
GET http://localhost:3003/api/blogs/614f1354ada571be52a00756

### Put
PUT http://localhost:3003/api/blogs/614f1371ada571be52a00758 HTTP/1.1
content-type: application/json

{
  "likes": 5
}

### Post
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer {{token}}

{
  "title": "Where is house?",
  "author": "Mossy Mark",
  "url": "https://example.com/taff",
  "likes": 15
}

### Post User
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
  "username": "hugh",
  "name": "hugh",
  "password": "abc"
}

### Delete
DELETE http://localhost:3003/api/blogs/61589754a8f3285404e5346d
Authorization: bearer {{token}}

### Post Login
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "hugh",
  "password": "abc"
}

### Reset Test DB
POST http://localhost:3003/testing/reset
content-type: application/json