### Info
GET http://localhost:3003/api/blogs

### Get
GET http://localhost:3003/api/blogs/614f1354ada571be52a00756

### Put
PUT http://localhost:3003/api/blogs/614f1371ada571be52a00758 HTTP/1.1
content-type: application/json

{
  "likes": 5
}

### Post
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "This Place",
  "author": "Linda McGuire",
  "url": "https://example.com/place",
  "likes": 14
}

### Post User
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
  "username": "h",
  "name": "Huw",
  "password": "abc"
}

### Delete
DELETE http://localhost:3003/api/blogs/614f1354ada571be52a00756